site_name: Thanatos

theme:
  name: material

plugins:
  - search
  - git-committers
  - git-revision-date-localized
  - mermaid2
  - autorefs

  - minify:
      minify_html: true
      minify_js: false
      htmlmin_opts:
          remove_comments: true

  - with-pdf:
      author: Pat McLean
      copyright: psmware ltd
      cover_subtitle: 'Codename: Thanatos  Î˜'
      toc_level: 2

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

nav:
  - Home: index.md
  - Getting Involved:
      - Contributing: contributing.md
      - Getting started: contributing/getting-started.md
      - Using the Repository: contributing/using-the-repo.md

