#  SPDX-License-Identifier: AGPL-3.0-only
#  Copyright (C) 2020-2021  Patrick McLean - psmware ltd

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

FROM postgres:13-alpine
COPY .devcontainer/init.sql /docker-entrypoint-initdb.d/
LABEL Name=thanatos-db Version=0.0.1
EXPOSE 5432

