# Generated by Django 3.2.3 on 2021-05-24 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_primarymetric_secondarymetric_tertiarymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.primarymetric')),
                ('secondary_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secondarymetric')),
                ('tertiary_metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tertiarymetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
